quasarframework/quasar-testing

packages/testing/install.js, packages/testing/prompts.js
When master testing extension is install, it asks to install other testing harnesses.
=> feat(testing): ask to install other harnesses during install

packages/e2e-cypress/base/test/cypress/plugins/index.js, packages/testing/index.js, packages/unit-jest/index.js, packages/unit-jest/install.js
=> fix(packages/*): remove useless console.log

packages/e2e-cypress/install.js, packages/e2e-webdriver/install.js, packages/quality/install.js, packages/testing/index.js, packages/testing/install.js, packages/unit-ava/install.js, packages/unit-jest/install.js
=> fix(packages/*): remove minimum quasar-app version

packages/testing/install.js
=> Urgent fix(testing)  wrong installation name

packages/unit-ava/base/test/ava/utils/index.js, packages/unit-jest/base/test/jest/utils/index.js
=> fix(ava, jest): remove broken babel transform

packages/e2e-webdriver/package.json
=> fix(wdio): upgrade wdio dep

packages/unit-ava/base/test/ava/___tests__/App.spec.js, packages/unit-ava/base/test/ava/___tests__/demo/QBtn-demo.vue
Tests copied from Jest, adapted for use with AVA
=> feat(ava): provide better demo test (from jest), fixes #37

packages/unit-jest/babelrc/_babelrc
Fixing a bug when generating coverage report
=> [Bug] dynamicImport issue in Babelrc

README.md
=> change `--add` to `add` 🖍

README.md
There was no way to go to Github via https://testing.quasar-framework.org/#high-level-overview
=> Added links to this github repo

README.md
=> docs: update README.md for testing-unit-jest upgrade

packages/unit-jest/README.md
Resolves #92 
- Added some markdown structure to surrounding topic headers for clarity
- Re-added and structured previous Webstorm instructions
- Added detailed VS Code syntax highlighting instructions
_Note: This is applied to the Jest docs but there's a duplicate section in the [main/AVA docs](https://github.com/quasarframework/quasar-testing/blob/dev/README.md#ava)
We could either replicate the instructions to there or DRY them up in a central place._
If adding a **new …
=> fix: #92 - Expand on SFC test instructions

packages/e2e-cypress/package.json, packages/unit-jest/package.json, packages/unit-jest/src/install.js, yarn.lock
=> Update deps for Jest and Cypress

packages/unit-vitest/src/helpers/layout-injections.ts, packages/unit-vitest/tsconfig.json, test-project-vite/test/vitest/__tests__/LayoutComponent.test.ts, test-project-vite/test/vitest/__tests__/demo/LayoutComponent.vue
=> fix(vitest): add more QLayout injections (fix #269)

packages/e2e-cypress/README.md
=> docs(cypress): fix README md link syntax

.github/PULL_REQUEST_TEMPLATE.md
=> docs: fix 404 of PR guide link

README.md
=> docs: add link to vitest documentation in README

packages/e2e-cypress/src/index.js
This is a candidate to fix #289.
=> fix(cypress): restore code coverage capability with dev server

packages/e2e-cypress/src/templates/no-typescript/test/cypress/support/component.js, packages/e2e-cypress/src/templates/typescript/test/cypress/support/component.ts, test-project-app/test/cypress/support/component.ts, test-project-vite/test/cypress/support/component.ts, test-project-webpack/test/cypress/support/component.ts
=> fix(cypress): import styles in correct order

packages/e2e-cypress/src/helpers/cct-dev-server/index.ts
=> fix(test): support both webpack v3,4 and vite v1,2

packages/e2e-cypress/README.md
See discussion in https://github.com/quasarframework/quasar-testing/issues/194#issuecomment-1682037177
It doesn't fix the issue, which is about adding a boot file loader helper, but it documents how to run test on components that depends on boot files.
=> docs(e2e-cypress): document how to replace boot files in component testing
