packages/testing/index.js
in the form of:
`quasar run @quasar/testing test -- --unit "jest --runInBand" "ava --serial" --e2e cypress --dev="--mode ssr"`
`--dev="--x"` is required, `--dev "--x"` will not work.
Also logs executed test runner command.
=> feat(testing): support runner and dev server args

packages/testing/install.js
=> [URGENT] fix(testing): execa not gettting imported

packages/unit-jest/base/test/jest/.eslintrc.js, testing-test/test/jest/__tests__/App.spec.js
The base template now includes a `.eslintrc.js` file that sets `env: { jest: true}}`. It also removes unused imports in the demo test to pass a linting run.
=> Fix(jest): demo test not obeying eslint, fixes #39

packages/unit-ava/src/base/test/ava/utils/index.js, packages/unit-jest/src/base/test/jest/utils/index.js
I've tried `quasar run @quasar/testing test -- --unit jest --dev` on a fresh Quasar install + testing extension installed with unit-jest harness
I got the following result (Windows 10, PowerShell):
```
RUN:  Running unit tests with jest
$ jest
FAIL  test/jest/__tests__/App.spec.js
Mount Quasar
√ passes the sanity check and creates a wrapper (5ms)
√ has a created hook
√ accesses the shallowMount (3ms)
√ sets the correct default data (1ms)
× correctly updates data …
```
=> fix with localVue.use(Quasar)

packages/e2e-cypress/src/base/test/cypress/support/index.js
I encountered error `err is not defined` and I found this is the fix for it
=> Fix, put the missing err parameter in the callback handler

packages/e2e-cypress/src/no-typescript/test/cypress/plugins/index.js
Copied this js [non-typescript] version directly from the latest [ts version](https://github.com/quasarframework/quasar-testing/blob/dev/packages/e2e-cypress/src/typescript/test/cypress/plugins/index.ts)
This was resolved in Cypress v3.0.3 and only applies to Chrome < 68
The workaround is no longer needed.
This would supersede #107 as the file modified in that PR no longer exists
and this matches the current `@quasar/testing-e2e-cypress` ts default.
If adding a **new feature**, …
=> chore(cypress): remove [js] workaround

packages/unit-jest/src/loader/test/loaders/jest-loader.js
jest.config.js matches test files on .jest.spec.js
jest-loader.js is exporting SFC tests with _jest.spec.js
This fix syncs the export+match so exported tests can be found by Jest
=> fix: #106 SFC test loader matcher

packages/unit-jest/src/no-typescript/jest.config.js, packages/unit-jest/src/typescript/jest.config.js
`test:unit:coverage` already exists and still works after this change.
This suggests `test:unit` should have coverage disabled by default as implemented by this change.
It is much more desirable to test repeatedly, but run coverage only periodically.
Closes #94 
=> chore(jest): disable coverage by default | Fix: #94

packages/unit-jest/src/no-typescript/jest.config.js, packages/unit-jest/src/typescript/jest.config.js
This config option causes vue-jest to transpile pug to html
without this config option pug is transpiled to xml
this causes errors with named slots which have empty values (not allowed in xml)
This config option applies to all users, even those who don't use pug
however it should have no effect for those who don't use pug
If this config option becomes accepted as the default in [vue-jest](https://github.com/vuejs/vue-jest/issues/175) then we can remove it from the config.
Closes: #87 
---
**The PR fulfills these …
=> fix(jest): vue-jest parse pug as html | fix: #87

packages/e2e-cypress/src/install.js
The npm scripts will not work on windows because of the single quotes.
This is already implemented in the `"concurrently:dev:jest"` npm script:
https://github.com/quasarframework/quasar-testing/blob/e2256cc78e15665fb362954ea7b579ca4297a46b/packages/unit-jest/src/install.js#L85
=> fix: cypress npm scripts for windows

packages/e2e-cypress/src/typescript/test/cypress/support/commands.ts
https://github.com/cypress-io/cypress/issues/7510 seems to have been released, so the TODO can be removed now
=> chore(TODO): cypress typescript fix has been released

packages/e2e-cypress/src/no-typescript/test/cypress/support/index.js, packages/e2e-cypress/src/typescript/test/cypress/support/index.ts
The workaround for the ResizeObserver exception should be updated for Cypress Version 4+, see: https://github.com/quasarframework/quasar/issues/2233#issuecomment-656554190
=> fix(e2e-cypress): update workaround for ResizeObserver exception

packages/unit-jest/README.md
Using `new Vuex({})` resulted in `TypeError: _vuex.default is not a constructor`.  Changed to `new Vuex.Store({})`.
=> Update Vuex instantiation

packages/unit-jest/README.md, packages/unit-jest/src/templates/no-typescript/test/jest/___tests__/MyDialog.spec.js, packages/unit-jest/src/templates/typescript/test/jest/___tests__/MyDialog.spec.js
=> fix: QDialog is not mounted in tests when used with mount() (fix #72)

packages/e2e-cypress/src/helpers/cct-dev-server/index.ts
=> fix: #223 - A package-manager-agnostic way to check the installed bundler

.github/CONTRIBUTING.md, README.md, packages/e2e-cypress/README.md, packages/testing/README.md, packages/unit-jest/README.md
When coming from the web to a random page, I had no idea what AE stood for.
=> Change "AE" to "App Extension (AE)" in docs

packages/e2e-cypress/src/index.js
**What kind of change does this PR introduce?**
- Feature
**Does this PR introduce a breaking change?**
- No
- It's submitted to the `dev` branch and _not_ the `master` branch
Sometimes it makes more sense to use `quasar build`+`quasar serve` instead of `quasar dev`, especially with Vite to avoid timeouts due to compiling on the fly. I would say it's a best practice in CI pipelines because using the production build would yield results closer to the real production environment. One could even use their actual webserver instead of `quasar serve` to also count it on the E2E tests. If you agree with any of these, I suppose we could add some information to the README file or even update the `test:e2e:ci` script template.
So, …
=> feat(cypress): allow code coverage on builds

packages/unit-vitest/README.md, packages/unit-vitest/src/helpers/install-quasar-plugin.ts, packages/unit-vitest/src/templates/no-typescript/test/vitest/___tests__/ExampleComponent.test.js, packages/unit-vitest/src/templates/no-typescript/test/vitest/___tests__/NotifyComponent.test.js, packages/unit-vitest/src/templates/typescript/test/vitest/___tests__/ExampleComponent.test.ts, packages/unit-vitest/src/templates/typescript/test/vitest/___tests__/NotifyComponent.test.ts, test-project-vite/test/vitest/__tests__/ExampleComponent.test.ts, test-project-vite/test/vitest/__tests__/LayoutComponent.test.ts, test-project-vite/test/vitest/__tests__/NotifyComponent.test.ts
Renamed installQuasarPlugin in installQuasar in accordance with the interface exported by the package @quasar/quasar-app-extension-testing-unit-vitest
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
Seems like vitest export is different from Jest and Cypress. If there is no technical reason behind, this could be misleading 😄
=> refactor(vitest): rename installQuasar in installQuasarPlugin

packages/e2e-cypress/README.md, packages/e2e-cypress/nyc-config-preset.json, packages/e2e-cypress/package.json, packages/e2e-cypress/src/index.js, yarn.lock
**What kind of change does this PR introduce?**
- Bugfix
**Does this PR introduce a breaking change?**
- No
- It's submitted to the `dev` branch and _not_ the `master` branch
When specifying the `exclude` option in `vite-plugin-istanbul`, it uses that instead of the ones in `.nycrc`. The ones specified in `exclude` option isn't accurate either. So, this PR updates the `exclude` in `.nycrc` to cover everything, then removes the `vite-plugin-istanbul`'s `exclude` option. Now, the excludes are more accurate, and the users will be able to add more excludes in their `.nycrc` files as they wish.
=> fix(cypress): do not override coverage exclude

packages/unit-vitest/package.json
update dependency vitest@0.30.1
update dependency vitest@^0.30.1
- update vitest from 0.29.x to 0.30.1 [vitest changelog](https://github.com/vitest-dev/vitest/releases/tag/v0.30.0)
=> update dependency vitest@^0.30.1

packages/e2e-cypress/src/helpers/v-model-adapter.ts
=> fix(cypress): await in vModelAdapter to ensure we don't need to call nextTick() in tests

packages/e2e-cypress/src/helpers/commands/cypress-overrides.ts, test-vite-app-v2/src/components/QuasarSelect.vue, test-vite-app-v2/src/components/__tests__/QuasarSelect.cy.ts
=> fix: improve Cypress select override

packages/unit-jest/jest-preset.mjs, packages/unit-jest/package.json, packages/unit-jest/src/index.js, packages/unit-jest/src/templates/no-typescript/test/jest/___tests__/MyButton.spec.js, packages/unit-jest/src/templates/no-typescript/test/jest/___tests__/MyDialog.spec.js, packages/unit-jest/src/templates/typescript/test/jest/___tests__/MyButton.spec.ts, packages/unit-jest/src/templates/typescript/test/jest/___tests__/MyDialog.spec.ts, test-webpack-app-v3/package.json, test-webpack-app-v3/quasar.extensions.json, test-webpack-app-v3/test/jest/__tests__/MyButton.spec.ts, test-webpack-app-v3/test/jest/__tests__/MyDialog.spec.ts, test-webpack-app-v3/yarn.lock, test-webpack-app-v4/package.json, test-webpack-app-v4/test/jest/__tests__/MyButton.spec.ts, test-webpack-app-v4/test/jest/__tests__/MyDialog.spec.ts, test-webpack-app-v4/yarn.lock, yarn.lock
- [x ] Bugfix
Only compatible with quasar >= 2.16.0, due to changes in the core quasar build modules (esm modules renamed to `quasar.client.js`. See [comment in the issue there](https://github.com/quasarframework/quasar/issues/17184#issuecomment-2158497588)
- [] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.
=> fix: fix compatibility with quasar 2.16.x (fix #373)
